---
sensor:
  - name: Total Consumed Energy
    state: >
          {% set energy_total = states('sensor.filtered_energy_total') | float(default = 0) * 1000 %}
          {% set yield_total = states('sensor.sensor.grid_power') | float(default = 0) %}

          {{ energy_total + yield_total | round(2, default = 0) }}
    unit_of_measurement: W
    state_class: measurement
    device_class: energy