---
sensor:
  - name: Power Dishwasher
    state: >
      {{ state_attr('switch.dishwasher', 'current_consumption') | float(default = 0) }}
    unit_of_measurement: W
    state_class: measurement
    device_class: power