---
id: '1638537922490'
alias: Control lights guestbedroom
description: ''
trigger:
- platform: device
  device_id: c7b4f79b908a526641cf36c1c4663f40
  domain: shelly
  type: long
  subtype: button
  id: long
- platform: device
  device_id: c7b4f79b908a526641cf36c1c4663f40
  domain: shelly
  type: single
  subtype: button
  id: single
- platform: device
  device_id: c7b4f79b908a526641cf36c1c4663f40
  domain: shelly
  type: double
  subtype: button
  id: double
- platform: device
  device_id: c7b4f79b908a526641cf36c1c4663f40
  domain: shelly
  type: triple
  subtype: button
  id: triple
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: long
    sequence:
    - type: toggle
      device_id: 2d991ad3c22f1d315fbbf40018c90e42
      entity_id: light.hallway
      domain: light
    - type: toggle
      device_id: 156ca73642961a69166a7ead4f7980b9
      entity_id: light.hallway_first_floor
      domain: light
  - conditions:
    - condition: trigger
      id: single
    sequence:
    - type: toggle
      device_id: 40f29352ce535663c7b91ad5ecaa2e97
      entity_id: light.guestbedroom
      domain: light
  - conditions:
    - condition: trigger
      id: double
    sequence:
    - type: toggle
      device_id: 156ca73642961a69166a7ead4f7980b9
      entity_id: light.hallway_first_floor
      domain: light
  - conditions:
    - condition: trigger
      id: tripple
    sequence:
    - type: toggle
      device_id: 2d991ad3c22f1d315fbbf40018c90e42
      entity_id: light.hallway
      domain: light
  default: []
mode: single
