substitutions:
  name: studyroom
  friendly_name: "Studyroom"


esphome:
  name: esphome-${name}
  platform: ESP8266
  board: nodemcuv2


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret IOT_SSID
  password: !secret IOT_SSID_PASSWORD

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-${friendly_name}"
    password: !secret ESPHOME_AP

captive_portal:

i2c:

text_sensor:
  - platform: template
    name: "Uptime ${friendly_name} Human Readable:"
    id: uptime_human
    icon: mdi:clock-start

sensor:
  - platform: uptime
    name: "Uptime ${friendly_name}"
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  - platform: wifi_signal
    name: "WiFi ${friendly_name}"
    update_interval: 15min

  - platform: bme280
    temperature:
      name: "Temperature ${friendly_name}"
      oversampling: 16x
    pressure:
      name: "Pressure ${friendly_name}"
    humidity:
      name: "Humidity ${friendly_name}"
    address: 0x77
    update_interval: 30s
    iir_filter: 2x
    
binary_sensor:
  - platform: gpio
    pin: 10
    name: "PIR ${friendly_name}"
    device_class: motion
